Repository Pradumnasaraf/open-source-with-pradumna, pull requests merged in 2022-06, with the labels that each got.

#48 docs: Add "How to clone a repo" in `How to` guide
  pages/How-to/guide/cloning-repo.md
Labels: documentation, enhancement, how-to

#51 Fix: path issue in `How to` section.
  .github/ISSUE_TEMPLATE/bug.yaml
  index.html
  pages/How-to/README.md
Labels: bug, documentation, how-to

#52 feat: Add `Faq,md` and some answer in that.
  README.md
  pages/Faq.md
Labels: documentation, enhancement, how-to

#53 feat: Added navbar and sidebar on the website
  _layouts/navbar.md
  _layouts/sidebar.md
  index.html
Labels: documentation, enhancement, how-to

#63 Fix: Typo in `Beginners.md`
  pages/Beginners.md
Labels: bug, documentation

#62 docs: Add process - "How to create issue (templates edition)"
  pages/How-to/guide/raise-issue-template.md
Labels: documentation, how-to

#69 ci: added greeting workflow
  .github/workflows/greetings.yml
Labels: feature

#70 ci: Added conventional release workflow
  .github/workflows/releases.yml
Labels: feature, CI

#57 docs: Add process - "how to create a PR Template"
  pages/How-to/guide/adding-pr-template.md
Labels: documentation, how-to
