Repository Pradumnasaraf/open-source-with-pradumna, pull requests merged in 2022-05, with the labels that each got.

#4 docs: V2 of repo
  README.md
  pages/Beginners.md
  pages/Bootcamp.md
  pages/Cheatsheet.md
  pages/Regular.md
  pages/Resources.md
Labels: documentation, enhancement

#5 Fix: fix minor typos
  README.md
  pages/Resources.md
Labels: documentation, enhancement

#6 fix: the wrong `<br>` tag in `pages/Cheatsheet.md`
  pages/Cheatsheet.md
Labels: documentation, enhancement

#19 fix: Fixed Typo in README
  README.md
Labels: documentation, enhancement

#40 fix: Chnage the tag from `<div>` to `<p>`
  pages/How-to/guide/adding-issue-template.md
  pages/How-to/guide/adding-pr-template.md
  pages/How-to/guide/adding-sponsor.md
  pages/How-to/guide/assigning-issue.md
  pages/How-to/guide/cloning-repo.md
  pages/How-to/guide/creating-pr.md
  pages/How-to/guide/linking-issue-with-pr.md
  pages/How-to/guide/rasing-issue.md
  pages/How-to/guide/reviewing-pr.md
Labels: bug, documentation

#42 docs: Update README.md
  README.md
Labels: documentation, enhancement

#44 docs: Add "How to create an Issue" in `How to` guide
  pages/How-to/guide/creating-an-issue.md
Labels: documentation, enhancement, how-to

#47 Fix: Typos in README.md
  README.md
Labels: bug, documentation, enhancement
